Dev
meh-daniel/SayMyNameApp pull request #1
Opened 2022-09-21 10:19 UTC by meh-daniel

2022-10-03 13:18 UTC, YanchenkOFF requested changes

2022-10-03 13:18 UTC, YanchenkOFF commented on app/src/main/java/meh/daniel/com/saymynameapp/data/Mappers.kt
> +internal fun List<CharacterNW>.toDomainFromNW() : List<Character>{
toDomain()

2022-10-03 13:18 UTC, YanchenkOFF commented on app/src/main/java/meh/daniel/com/saymynameapp/data/Mappers.kt
> +internal fun CharacterNW.toDomainFromNW(): CharacterDetails {
toDomain() - зачем указывать fromNW? если данную функцию ты сможешь применить только к NW моделям

2022-10-03 13:18 UTC, YanchenkOFF commented on app/src/main/java/meh/daniel/com/saymynameapp/data/Mappers.kt
> +        )
it.toDomain()

2022-10-03 13:18 UTC, YanchenkOFF commented on app/src/main/java/meh/daniel/com/saymynameapp/data/Mappers.kt
> +internal fun CharacterNW.toDetailSWFromNW(): CharacterDetailsSW {
toSW()

2022-10-03 13:18 UTC, YanchenkOFF commented on app/src/main/java/meh/daniel/com/saymynameapp/data/Mappers.kt
> +        )
it.toSW()

2022-10-03 13:50 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/data/Mappers.kt
> +        )
Там один мапер похожий, и поэтому один из оставил toDomainFromSW(), а остальные привёл в стандартный вид

2022-10-03 14:53 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/data/Mappers.kt
> +        )
Так, ну тут я исправил тоже

2022-10-03 14:55 UTC, tusxxx requested changes

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/core/BaseViewModel.kt
> +abstract class BaseViewModel : ViewModel()
.зачем пустой абстрактный класс?

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/core/BaseFragment.kt
> +abstract class BaseFragment<ViewModel: BaseViewModel, Binding : ViewBinding>(
https://stackoverflow.com/questions/64819181/how-to-make-basefragment-with-view-binding
.решение, которое устаялось на других проектах.

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/core/BaseFragment.kt
> +    protected open fun initialize() {
.зачем делать пустые функции с возможностью оверрайда?

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/Mappers.kt
> +        )
.сделать маппер CharacterNW -> Character чтобы написать it.toDomain()

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/Mappers.kt
> +        )
.аналогично комментарию моему выше

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/Mappers.kt
> +internal fun List<CharacterSW>.toDomainFromSW(): List<Character> {
.какой блин domainFromSW ?))
.просто toDomain()
.если будет ругаться на одинковый нейминг - Java аннотация из alt+enter в помощь

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            val listOf = episode.listIdCharacter.split(" ").toList()
.что за переменная?
.ренейм

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +                if(listOf[i].isNotBlank()) {
?

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            for(i in listOf.indices) {
forEach ?

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +        return try {
try - рефактор

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            val listCharactersOfEpisode: List<String> = episodeNW[0].characters
.first()
.у тебя странная мода нейминга переменных
.обычно list ставят в конце heroList, idList и т.д.

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            val listHero = mutableListOf<CharacterSW>()
.список героев или персонажей?

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            var listId = ""
??

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            for(i in listOf.indices) {
.мапперы для чего?)

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            val nameEpisode = episodeNW[0].title
.ты, считай, всеми этими махинациями выполняешь маппинг

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            Episode(
.последней строчкой образно должно быть api.getEpisode().toDomain()
.тут совсем много лишнего
.у тебя репозиторий берет на себя маппинг

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            Episode(
.методы ниже куда образцовее

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            val characterDetails: CharacterNW = api.getHeroById(id)[0]
[0] = .first()

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            val listCharacter = dataBase.serialDao().findCharacterByName("$name%").toDomainFromSW()
.нельзя просто name прокинуть в findCharacterByName()?

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            if(listCharacter.isEmpty()) listCharacter else throw Throwable("isEmptyListCharacter")
.то есть, если список пустой, вернём его, если с элементами, кинем throwable?

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/nw/BreakingBadApi.kt
> +        @Query("name", encoded = true) name: String
.зачем encoded ?

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/di/NetworkModule.kt
> +    @Reusable
.почему reusable?

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterdetail/CharacterDetailInfoFragment.kt
> +            with(binding) {
.всю эту штуку рефакторить
.Еще, что мешало сделать, который после загрузки исчезал?
.штуку с отдельным исчезнавением и появлением вюшки по стейту уже не практикуют, имхо

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterdetail/CharacterDetailInfoViewModel.kt
> +    val heroState: Flow<CharacterDetailInfoState> = _heroState.asStateFlow()
.Почему Flow<>?

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterdetail/CharacterDetailInfoViewModel.kt
> +                    if (heroData.name.isEmpty()) {
isBlank()

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterlist/CharacterAdapter.kt
> +        fun from(parent: ViewGroup): RecyclerView.ViewHolder {
.заренейми функции эти

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterlist/CharacterListFragment.kt
> +    }, {
.именуй лямбды

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterlist/CharacterListFragment.kt
> +            with(binding) {
.рефактор

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterlist/CharacterListFragment.kt
> +        bundle.putString("IdHero", id.toString())
.константа

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterlist/CharacterListViewModel.kt
> +    private val _numberCurrentEpisode = MutableStateFlow(1)
.константа

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterlist/CharacterListViewModel.kt
> +                    if (heroData.name.isEmpty()) {
isBlank

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/charactersearch/CharacterSearchAction.kt
> +interface CharacterSearchAction {
.что это?)

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/charactersearch/CharacterSearchFragment.kt
> +            when(action) {
when для одного is ?))

2022-10-03 14:55 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/charactersearch/CharacterSearchViewModel.kt
> +                    if (heroData.isEmpty()) {
isBlank

2022-10-03 15:08 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/core/BaseViewModel.kt
> +abstract class BaseViewModel : ViewModel()
Ну у меня тогда вот фрагменты когда наследуются от Базового фрагмента имеют в дженерике название viewModel к которым они привязаны, тем самым я хотел как то код обобщить

2022-10-03 15:14 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/core/BaseFragment.kt
> +    protected open fun initialize() {
Всё это сделано лишь для одной цели- свести повторяющийся код к одному виду. До этого у меня в проектах получается были участки кода где я должен например был проинициализировать view или адаптер, и я нашёл решение, что можно просто создать в базовом фрагменте методы пустые, и только в них например инициализировать view и адаптеры. А в каком нибудь setupListeners все слушатели кнопок. А в setupSubscribers() все слушатели данных. По итогу у меня стало чутка попроще если знать контекст который вот я написал

2022-10-03 15:35 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +                if(listOf[i].isNotBlank()) {
Я слабо понимаю как работают таблицы многие ко многим в room, и поэтому придумал костыль, что вместо дополнительной таблицы со значением эпизод -> персонаж - я просто их имена сохранял в переменную, делая оступ и сохранял в таблицу как одну строку. И когда я получаю эту строку из базы данных, то я как бы делю на значения все имена, и последним значением у меня есть пустота в один char, и вот этот if помогает избежать вот это последнего значения

2022-10-03 15:37 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            for(i in listOf.indices) {
Я делал forEach, но у меня тогда значения сразу возвращались, и это по итогу ещё хуже всё выглядело, и поэтому чисто for оставил

2022-10-03 15:39 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +        return try {
не совсем понял что именно рефакторить нужно, но я сделал через = try

2022-10-03 15:40 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            val listHero = mutableListOf<CharacterSW>()
Персонажей, исправил

2022-10-03 15:45 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            val listCharacter = dataBase.serialDao().findCharacterByName("$name%").toDomainFromSW()
Можно, но тогда чтобы найти персонажа по имени, придётся вводить полное имя без ошибок, иначе будет возвращаться пустой список

2022-10-03 15:47 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            if(listCharacter.isEmpty()) listCharacter else throw Throwable("isEmptyListCharacter")
Это звучит очень безумно, но именно так. Ибо у меня в presentation слое обработка идёт даже на пустые значения, а он именно пустой возвращает если ничего не находит. А бизнес логика такова что я должен идти в сеть, если ничего не найду в бд. Поэтому всё именно так

2022-10-03 15:54 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/data/nw/BreakingBadApi.kt
> +        @Query("name", encoded = true) name: String
Ты не поверишь но мою головную боль решил Jake Wharton https://github.com/square/retrofit/issues/1199 
В айпи breakingBad необходимо для поиска персонажа по имени в пустые строки между именем и фамилией вставлять +, а Retrofit + конвертирует в другие символы. И тут нужно было создавать либо интерсептор прям навороченный в котором я бы это предовращал и что я сделал(ещё был вариант сделать кастомный из okHttps адаптер в ретрофит билдер), или по проще- написать encoded и не давать конвертировать +

2022-10-03 16:01 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/charactersearch/CharacterSearchFragment.kt
> +            when(action) {
Ну вообще тип насколько я смог преисполниться в этой теме, то Action общепринято обрабатывать через when, так как только один action в один момент времени, поэтому не стал ничего иного мудрить...
А так я стараюсь код по умолчанию оставлять расширяемым, если какие то участки кода можно будет расширить

2022-10-03 16:07 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/charactersearch/CharacterSearchViewModel.kt
> +                    if (heroData.isEmpty()) {
а шо а почему у меня же это коллекция а не строка. Тип тут ведь ток empty и подойдёт

2022-10-03 16:08 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/charactersearch/CharacterSearchAction.kt
> +interface CharacterSearchAction {
А это паттерн MVI, который я сюда внедряю... И суть его такова, что у пользователя есть намерение, и это намерение можно отобразить через интерфейс, как например этот. В общем, я вынес возможные действия пользователя в отдельный интерфейс

2022-10-03 16:19 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterlist/CharacterAdapter.kt
> +        fun from(parent: ViewGroup): RecyclerView.ViewHolder {
Ну я заренеймил на onCreateViewHolder как бы банально не звучало,но по сути это можно ещё назвать как onCreate или вообще onCreateView. Тут функция ещё такая, что она должна с именем viewHolder сочитаться, так как он с классом ток используется. OnCreate лучше же будет?

2022-10-03 16:25 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterlist/CharacterListFragment.kt
> +    }, {
Омг, а вопрос, а если у меня лямбда Unit возвращает, то я могу в этом случае не именовать её?

2022-10-03 16:29 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/data/Mappers.kt
> +internal fun List<CharacterSW>.toDomainFromSW(): List<Character> {
вау, круто, про антоацию эту забыл

2022-10-03 16:38 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/di/NetworkModule.kt
> +    @Reusable
Грубо говоря, насколько я понял- reusable, это как синглтон, ток со скоупом, что позволяет например его убрать из памяти когда он например помог собрать retrofitBuilder, и является таким полезным решением для производительности. Я не прям чтоб хорошо его знаю- ток пару статей прочитал, но потихоньку начинаю в некоторых местах использовать

2022-10-04 02:16 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/core/BaseViewModel.kt
> +abstract class BaseViewModel : ViewModel()
ViewModel же можно вписать было

2022-10-04 02:16 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/core/BaseViewModel.kt
> +abstract class BaseViewModel : ViewModel()
.в generic

2022-10-04 02:16 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +                if(listOf[i].isNotBlank()) {
.gson почему не использовать тогда, который позволит сериализовать из строки в экземпляр и обратно?

2022-10-04 02:20 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +        return try {
.код внутри try)

2022-10-04 02:28 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            if(listCharacter.isEmpty()) listCharacter else throw Throwable("isEmptyListCharacter")
.то есть, если у тебя в бд есть записи, то ты идёшь в сеть?

2022-10-04 02:30 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/data/SerialRepositoryImpl.kt
> +            if(listCharacter.isEmpty()) listCharacter else throw Throwable("isEmptyListCharacter")
.с бд придёт список с элементами -> он не пустой -> кидаешь throwable -> идёшь в сеть
.а смысл тогда от бд, если оттуда значения не берешь, кроме пустого списка?

2022-10-04 02:35 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterlist/CharacterAdapter.kt
> +        fun from(parent: ViewGroup): RecyclerView.ViewHolder {
onCreateViewHolder - это колбэк, вызываемая при создании vh
createViewHolder - функция создающая viewHolder
.выбирай)

2022-10-04 02:37 UTC, tusxxx requested changes

2022-10-04 02:37 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterlist/CharacterListFragment.kt
> +    }, {
.я про другое
.параметры-лямбды именуй
someFun(
param1 = { asd: ASd ->
asdasd.asd
}, 
param2 - {dsa: dsa ->
}
)

2022-10-04 02:37 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterlist/CharacterListViewModel.kt
> +                    _characterListState.value = when (e) {
when (e) {
else ->
}
.ну совсем уж комично смотрится

2022-10-04 06:05 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/core/BaseViewModel.kt
> +abstract class BaseViewModel : ViewModel()
Точно!

2022-10-04 06:06 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/core/BaseFragment.kt
> +abstract class BaseFragment<ViewModel: BaseViewModel, Binding : ViewBinding>(
Я попытаюсь переделать под это решение тогда всё

2022-10-04 06:23 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/core/BaseFragment.kt
> +abstract class BaseFragment<ViewModel: BaseViewModel, Binding : ViewBinding>(
Так, ну я почитал, там несколько примеров реализаций базового фрагмента, и поэтому решил не особо менять ибо не знаю который именно как бы у вас на проде используется- и был бы рад увидеть вариант какой либо, но если так смотреть то у меня вариант отличается тем что onCreateView и  onViewCreated исключены из использования во фрагментах(так как стоит модификатор final) и у меня есть отдельный метод для того чтобы проиницилизировать Binding, по моему этот варик по круче будет, хотя я возможно не знаю некоторых вариантов использования эти функций, где бы понадобилось из базового фрагмента оверайдить

Вопрос, на проде используется эта библиотека?
https://github.com/androidbroadcast/ViewBindingPropertyDelegate

2022-10-04 06:38 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterlist/CharacterListViewModel.kt
> +                    _characterListState.value = when (e) {
О боже, это я уже случайно оставил когда убирал отлов ошибок

2022-10-04 06:48 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterlist/CharacterListViewModel.kt
> +                    _characterListState.value = when (e) {
Воух, я вообще не знал что лямбды можно именовать, круто...

2022-10-04 06:58 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterdetail/CharacterDetailInfoViewModel.kt
> +    val heroState: Flow<CharacterDetailInfoState> = _heroState.asStateFlow()
Вообще можно и без явного указания типа, то я сделал так чисто для простоты чтения/понимания кода в этих участках

2022-10-04 06:59 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/saymynameapp/presentation/screens/characterlist/CharacterListFragment.kt
> +    }, {
Воух, я вообще не знал что лямбды можно именовать, круто...

2022-10-10 04:26 UTC, merged